# -*- coding: utf-8 -*-
"""college_cache.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sz0os82tB9XaO6oRHDLdVyvOkRHXG_vn
"""

!pip install redis

# start redis server

!apt-get install redis-server
!redis-server --daemonize yes

import redis

redis_client = redis.Redis(
    host='localhost',
    port=6379,
    decode_responses=True  # important: returns strings not bytes
)

# can be adjusted later - we do want up to date college information
CACHE_TTL = 60 * 60 * 24 * 7  # 7 days

def scrape_college_website(url: str) -> str:

    # Check Redis
    cached = redis_client.get(url)

    if cached:
        print(f"[REDIS CACHE HIT] {url}")
        return cached

    # scrape
    try:
        print(f"[SCRAPING] {url}")

        headers = {"User-Agent": "Mozilla/5.0"}
        resp = requests.get(url, headers=headers, timeout=10)
        resp.raise_for_status()

        soup = BeautifulSoup(resp.text, "html.parser")

        for tag in soup(["script", "style", "nav", "footer"]):
            tag.decompose()

        text = soup.get_text(separator="\n", strip=True)
        text = text[:4000]

        # score in Redis with TTL
        redis_client.setex(url, CACHE_TTL, text)

        return text

    except Exception as e:
        return f"Error scraping {url}: {e}"

# CACHE AGENT RESPONSES - prevent evaluator from reruning
def run(query: str, student_context: dict = {}) -> dict:
    cache_key = f"college:{query.strip().lower()}"

    cached = redis_client.get(cache_key)
    if cached:
        print("[AGENT CACHE HIT]")
        return {"response": cached}

    response_text = asyncio.run(_run())

    redis_client.setex(cache_key, 3600, response_text)  # agent response cache - 1 hour

    return {"response": response_text}