# -*- coding: utf-8 -*-
"""EvaluatorAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysvPjEWJdbHuPAirK6hMtxlxAC6cnLhi
"""

# import subagents
import app as rag_agent
from memory import load_profile, init_db
from agent import run as memory_run
from events_agent.main import run as events_run
import college_subagent as college_agent

#config

GROQ_API_KEY = os.environ["GROQ_API_KEY"]
GROQ_MODEL = "llama-3.3-70b-versatile"
AVAILABLE_AGENTS = ["rag_agent", "memory_agent", "college_agent", "events_agent"]

AGENT_TYPE_MAP = {
    "rag_agent": "rag",
    "college_agent": "college",
    "events_agent": "events",
    "memory_agent": "memory"
}

agent_type = AGENT_TYPE_MAP["college_agent"]

#evaluator function
import json

def evaluate_response(user_query, agent_response, agent_type, retrieved_context=None):
    groq = _get_groq()

    prompt = f"""
You are an evaluation agent.

You will be given:
- user_query
- agent_response
- agent_type
- retrieved_context (may be None)

Evaluate the response.

GLOBAL METRICS (1-5):
- relevance: Does it answer the query?
- correctness: Is it accurate?
- clarity: Is it easy to understand?
- completeness: Is anything missing?
- coherence: Is it well-structured?

AGENT-SPECIFIC METRICS:

If agent_type == "college":
- factual_accuracy
- usefulness_for_student

If agent_type == "rag":
- groundedness
- hallucination
- faithfulness
- context_relevance

INSTRUCTIONS:
- Be strict and critical
- Use only the provided inputs
- If retrieved_context is None, skip RAG metrics
- Keep reasoning to 1 sentence per metric
- Return ONLY valid JSON (no explanation outside JSON)

OUTPUT FORMAT:

{
  "scores": {
    "relevance": 1,
    "correctness": 1,
    "clarity": 1,
    "completeness": 1,
    "coherence": 1
  },
  "agent_specific": {},
  "reasoning": {
    "relevance": "",
    "correctness": "",
    "clarity": "",
    "completeness": "",
    "coherence": ""
  },
  "summary": ""
}

INPUT:

user_query: {user_query}

agent_response: {agent_response}

agent_type: {agent_type}

retrieved_context: {retrieved_context}
"""

# send evaluation prompt to the LLM (groq) -> get response from the prompt
    completion = groq.chat.completions.create(
        model=GROQ_MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    raw_output = completion.choices[0].message.content

# convert raw_output text to structured output -> python dictionary
    try:
        parsed = json.loads(raw_output)
        return parsed
    except Exception:
        return {
            "error": "Invalid JSON",
            "raw_output": raw_output
        }

# if below certain threshold, rerun the specific subagent and then evaluate again
def is_low_quality(evaluation):
    scores = evaluation.get("scores", {})

    if scores.get("relevance", 5) < 3:
        return True
    if scores.get("correctness", 5) < 3:
        return True

    return False

def build_retry_prompt(original_query, response, evaluation):
    issues = evaluation.get("issues", [])
    summary = evaluation.get("summary", "")

    feedback = "\n".join(f"- {issue}" for issue in issues)

    return f"""
The previous response was not good enough.

Issues identified:
{feedback}

Summary:
{summary}

Please generate a better response to the original query:

{original_query}
"""

def run_with_retry(agent_name, run_fn, query, student_context=None, max_retries=1):

    agent_type = AGENT_TYPE_MAP[agent_name]

    # Step 1: initial run
    result = run_fn(query, student_context)
    response = result["response"]

    # Step 2: evaluate
    evaluation = evaluate_response(
        user_query=query,
        agent_response=response,
        agent_type=agent_type
    )

    # Step 3: retry if needed
    retries = 0
    while is_low_quality(evaluation) and retries < max_retries:
        print("Low quality detected. Retrying...")

        retry_query = build_retry_prompt(query, response, evaluation)

        result = run_fn(retry_query, student_context)
        response = result["response"]

        evaluation = evaluate_response(
            user_query=query,
            agent_response=response,
            agent_type=agent_type
        )

        retries += 1

    return {
        "response": response,
        "evaluation": evaluation,
        "retries": retries
    }